### ISSUE TITLE
ineffective test for null

### ISSUE THREAD

**Issue by arnaudlacour** [pingidentity/pingid-api-playground#4]
There is a test that will fail with NPE that we would to well to fix

**Comment by arnaudlacour** [comment]
arnaudlacour-r:pingid arnaudlacour$ git diff -b master Operation.java
diff --git a/src/main/java/com/pingidentity/developer/pingid/Operation.java b/src/main/java/com/pingidentity/developer/pingid/Operation.java
index ab66198..f7a1cbf 100644
--- a/src/main/java/com/pingidentity/developer/pingid/Operation.java
+++ b/src/main/java/com/pingidentity/developer/pingid/Operation.java
@@ -354,7 +354,7 @@ public class Operation {

                JSONObject formParameters = new JSONObject();
                formParameters.put("sp_name", application.getName());
-               if (application.getLogoUrl() != null || !application.getLogoUrl().isEmpty()) {
+               if (application.getLogoUrl() != null && !application.getLogoUrl().isEmpty()) {
                        formParameters.put("sp_logo", application.getLogoUrl());
                }

**Comment by asafd1** [comment]
thanks! can you submit a merge request?
