### ISSUE TITLE
the default apiVersion should be 4.9, to allow for multi-device support

### ISSUE THREAD

**Issue by cakirkh** [pingidentity/pingid-api-playground#7]
pingidentity/pingid-api-playground/blob/master/src/main/java/com/pingidentity/developer/pingid/Operation.java

`private final String apiVersion = "4.6"`
should be 
`private final String apiVersion = "4.9";`

**Comment by asafd1** [comment]
please create a [pull request](https://yangsu.github.io/pull-request-tutorial/) (you can use a forked repository)

**Comment by jeremybcarrier** [comment]
Updated default version to 4.9
